export default theme => ({
  rootWrapper: {
    position: 'relative',
    width: '0',
    height: '0',
    visibility: 'hidden',
    margin: '0 !important',
    padding: '0 !important',
  },
  root: {
    visibility: 'visible',
    position: 'absolute',
    bottom: '5px',
    right: '0',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100px',
    minHeight: '30px',
    padding: '5px',
    fontSize: theme.fontSize,
    borderRadius: theme.borderRadius,
    backgroundColor: theme.brandLightGrayColor,
    '&:before': {
      position: 'absolute',
      content: '""',
      bottom: '-10px',
      width: '0',
      height: '0',
      borderLeft: '10px solid transparent',
      borderRight: '10px solid transparent',
      borderTop: `10px solid ${theme.brandLightGrayColor}`,
    },
  },
});
